/**
 * @name leekslazylogger
 * @author eartharoid <contact@eartharoid.me>
 * @description An easy-to-use and lightweight console logger for Node.JS
 * @license MIT
 * 
 * log file header template- cleans up main file
 * 
 */

const timestamp = require("dtstamp");

module.exports = (o, v) => {
    return `\n<-<-<================================================================================>->->
    File generated by leeksLazyLogger v${v} by eartharoid (go.eartharoid.me/lll)
    ${o.name} | Log File
    ${timestamp('DDDD, n_D MMMM YYYY, hh:mm ampm')} (${Intl.DateTimeFormat().resolvedOptions().timeZone}) -->
    Node: ${process.version} on '${process.platform}' | Time format: '${o.timestamp}' | Date format: '${o.dateFormat}'
<-<-<================================================================================>->->\n`
};