# Project information
site_name: leekslazylogger
site_description: Documentation for leekslazylogger - an easy-to-use and lightweight Node.JS logger with file support, colours, and timestamps.
site_author: eartharoid
site_url: https://logger.eartharoid.me
#nav:
#  - Home: index.md
#  - NPM: https://www.npmjs.com/package/leekslazylogger
#  - Yarn: https://yarnpkg.com/package/leekslazylogger

# Repository
repo_name: eartharoid/leekslazylogger
repo_url: https://github.com/eartharoid/leekslazylogger

# Copyright
copyright: '&copy; 2020 Isaac Saunders'

# Configuration
theme:
  name: material
  language: en
  palette:
    # scheme: slate
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - instant
  logo: /img/logo.png
  favicon: /img/favicon.ico

# Extras
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://eartharoid.me
    - icon: fontawesome/brands/github-alt
      link: https://github.com/eartharoid
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/eartharoid
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/eartharoid

# Google Analytics
#google_analytics:
#  - UA-XXXXXXXX-X
#  - auto

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - awesome-pages

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
# pymd
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
