version: 2.1

general:
  branches:
    only:
     - master

orbs:
  node: circleci/node@3.0.0
  python: circleci/python@0.3.0

jobs:
  test:
    executor: node/default
    steps:
      - run:
          command: npm test
          name: Node test
  deploy:
    executor: python/default
    steps:
      - add_ssh_keys:
          fingerprints:
            - "41:1e:44:b7:08:c8:a0:bf:d1:27:20:54:dd:b6:72:f2"
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: mkdocs gh-deploy
          name: Build & deploy wiki to GitHub Pages

workflows:
  main:
    jobs:
      - test
      - deploy