module.exports = {
	colours: {
		'&0': 'black',
		'&1': 'blue',
		'&2': 'green',
		'&3': 'cyan',
		'&4': 'red',
		'&5': 'magenta',
		'&6': 'yellow',
		'&7': 'blackBright',
		'&8': 'whiteBright',
		'&9': 'blueBright',
		'&a': 'greenBright',
		'&b': 'cyanBright',
		'&c': 'redBright',
		'&d': 'magentaBright',
		'&e': 'yellowBright',
		'&f': 'white',
		'&!0': 'bgBlack',
		'&!1': 'bgBlue',
		'&!2': 'bgGreen',
		'&!3': 'bgCyan',
		'&!4': 'bgRed',
		'&!5': 'bgMagenta',
		'&!6': 'bgYellow',
		'&!7': 'bgBlackBright',
		'&!8': 'bgWhiteBright',
		'&!9': 'bgBlueBright',
		'&!a': 'bgGreenBright',
		'&!b': 'bgCyanBright',
		'&!c': 'bgRedBright',
		'&!d': 'bgMagentaBright',
		'&!e': 'bgYellowBright',
		'&!f': 'bgWhite',
	},
	styles: {
		'&i': 'inverse',
		'&j': 'dim',
		'&k': 'blink',
		'&l': 'bold',
		'&m': 'strikethrough',
		'&n': 'underline',
		'&o': 'italic',
		'&p': 'overline',
		'&r': 'reset',
	}
};