/**
 * @name leekslazylogger
 * @author eartharoid <contact@eartharoid.me>
 * @description An easy-to-use and lightweight Node.JS logger with file support, colours, and timestamps.
 * @license MIT
 *
 * log file header template - cleans up main file
 *
 */

const timestamp = require('@eartharoid/dtf');
const { version, author, homepage } = require('../package.json');

const platform = () => {
	switch (process.platform.toLowerCase()) {
      	case 'aix': return 'Unix';
	    case 'sunos': return 'SunOS';
	    case 'win32': return 'Windows';
	    case 'linux': return 'Linux';
    	case 'darwin': return 'MacOS';
	    case 'freebsd': return 'BSD';
	    case 'openbsd': return 'BSD';
	    case 'android': return 'Android';
    	default: 'unknown platform';
	}
};

module.exports = (o) => {
	return `
    \n<-<-<================================================================================>->->
    File generated by leekslazylogger v${version} by ${author.name} (${homepage})
    ${o.name} | Log File
    ${timestamp('DDDD, n_D MMMM YYYY, HH:mm ampm')} (${Intl.DateTimeFormat().resolvedOptions().timeZone}) -->
    Node: ${process.version} on '${platform()}' | Time format: '${o.timestamp}' | Date format: 'YYYY-MM-DD'
<-<-<================================================================================>->->\n\n
`;
};